### ISSUE TITLE
[Workflow] Improving login system

### ISSUE THREAD

**Issue by nonunknown** [sketchfab/blender-plugin#44] opened 2021-07-16 17:14 UTC
Actually my sketchfab account, I can only login at the site via github account or google mail (if I can remember well)

So how I'm suppose to login?

**Improving login suggestions**

* Let the user put its API token
* The login button send to a login page with the default browser then, return to blender

**Comment by melMass** [comment] 2021-08-23 15:25
Duplicate of #11

**Comment by PadreZippo** [comment] 2023-12-13 20:22
You can now authenticate using your API Token:

![image](https://github.com/sketchfab/blender-plugin/assets/7097291/690c8a33-f23a-4105-be39-f7413cbb9882)

**Closed by PadreZippo** 2023-12-13 20:22 UTC
