### ISSUE TITLE
Importing a model switches render engine to Eevee

### ISSUE THREAD

**Issue by AdityaGupta1** [sketchfab/blender-plugin#14] opened 2020-08-22 23:51 UTC
I use Cycles for my renders, but whenever I import a model, it switches the render engine to Eevee. Is there an option to turn this off or is it a bug?

**Comment by PadreZippo** [comment] 2020-08-24 14:12
I suspect this is the intended behavior, as Eevee allows the closest match between Sketchfab's and Blender's PBR channels, but I will let @loicSketchfab confirm.

**Comment by llriu** [comment] 2021-06-10 09:41
From my experience, the materials work fine in Cycles. It's annoying to have to switch back to cycles every time I import a model.

**Comment by loicSketchfab** [comment] 2022-03-22 09:37
👋 
We've included a fix for this issue in version [1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon, to keep either Cycles or Eevee as a render engine upon import.
Closing this issue, but feel free to reopen if something is off for your usecase 👍

**Closed by loicSketchfab** 2022-03-22 09:37 UTC

**Comment by AdityaGupta1** [comment] 2022-03-22 17:06
Seems to work perfectly now. Thank you very much!
