### ISSUE TITLE
Every model import resets render engine back to Eevee

### ISSUE THREAD

**Issue by jsperl64** [sketchfab/blender-plugin#46] opened 2021-08-13 23:29 UTC
...instead of leaving Cycles selected. Blender 2.93 E-Cycles edition.

**Comment by PadreZippo** [comment] 2021-08-16 14:25
Hi there,

I think this is the expected behavior because we depend in Eevee to match our PBR material channels to Blender. Maybe @loicSketchfab can confirm though.

**Comment by AdityaGupta1** [comment] 2022-02-05 18:30
This is referenced in #14 as well, but the materials work fine in Cycles. An option to disable the automatic switching to Eevee would be very helpful. I've often imported a model with Cycles viewport rendering enabled only for it to switch to Eevee, meaning Blender hangs while loading all of my shaders for Eevee viewing. This is especially unhelpful when I'm using models that have many HD textures, as I prefer to not use Eevee preview and stick to gray flat shaded and Cycles viewport rendering.

**Comment by loicSketchfab** [comment] 2022-03-22 09:37
👋 
We've included a fix for this issue in version [1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon, to keep either Cycles or Eevee as a render engine upon import.
Closing this issue, but feel free to reopen if something is off for your usecase 👍

**Closed by loicSketchfab** 2022-03-22 09:37 UTC
