### ISSUE TITLE
no thumbnail display

### ISSUE THREAD

**Issue by adhhrg** [sketchfab/blender-plugin#55] opened 2021-11-13 20:14 UTC
no thumbnail display
<img width="627" alt="blender_9q87R5sTjD" src="https://user-images.githubusercontent.com/63681591/141657758-b614d784-e7f5-498e-a40e-8c445f621997.png">

**Comment by InfinityCg** [comment] 2021-12-23 17:05
Having the same issue, but I don't think it will be fixed soon
Better open old blender version, download in it and copy paste

**Comment by loicSketchfab** [comment] 2022-03-22 09:31
The [version 1.5.0 of the addon](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) (compatible from 2.83 to 3.2 alpha) has a fix for this issue, which presented itself because of some Blender python libs not handling multiple simultaneous download requests for the models thumbnails.

I managed to reproduce the issue with slow connections and this release fixes the issue on my side, but feel free to reopen this ticket if the bug still appears 👍

**Closed by loicSketchfab** 2022-03-22 09:31 UTC

**Comment by InfinityCg** [comment] 2022-03-22 11:01
Hello @loicSketchfab 
Thanks a lot for the update and fixing the thumbnail issue, The issue has successfully been resolved and the plugin is working as expected. 

I thought there might have been some problem with the code and tried browsing it with my dummy python skills lol, thanks for the fix

**Comment by loicSketchfab** [comment] 2022-03-22 13:59
Glad to hear that !
Sorry if this came a little late, but do not hesitate to report issues if other strange behaviour pop-up, we'll keep a closer watch from now on.

**Comment by InfinityCg** [comment] 2022-03-22 16:29
@loicSketchfab Sorry once again, but I think that something happened after I tried to install the plugin to version 3.1(Stable), the thumbnail problem is acting up again 100% of the times in version 3.0(stable) and 3.1 [Screenshot](https://imgur.com/a/aNWpsYe)

If there is any way in which I could assist you please do tell

**Comment by loicSketchfab** [comment] 2022-03-23 10:59
Hey @InfinityCg 👋 

I saw you responded then deleted your response, telling the issue still appeared.
I'm under the feeling that maybe another step needed would be to specify a custom directory in which you have a writing access in the addon preferences under "Download directory" (see screenshot [here](https://github.com/sketchfab/blender-plugin#installation)).

If you solved you problem, happy in any case, but I'd be glad to know if this is the step you took to solve it, to maybe make it more clear on the addon README.

If it's still happening, any info located in your system console (Window->Toggle system console on Windows, or by launching Blender from a terminal on Mac or Linux) would be really helpful, along with knowing if maybe you work on a specific setup (do you have a user which is not administrator, things like that...) and OS specifications.

Cheers !
